#!/bin/bash

# List of branches to pull
branches=("main" "joy" "rukhsana" "newashik" "sabbirrsec")

# Loop through the branches and pull changes
for branch in "${branches[@]}"; do
  echo -e "\nPulling from $branch"
  git checkout "$branch"
  git pull
done

